Implemented Datastorage with overkill
ArchipelagoMW/Archipelago.MultiClient.Net pull request #37
Opened 2022-03-06 23:37 UTC by JarnoWesthof

2022-03-14 22:36 UTC, Ijwu requested changes
Sorry to nitpick, I had nothing else to complain about. This looks good, code wise! Wow, this is well done.

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +DataStorage support is included in the library. you may save values on the archipelago server in order to share there across other players or to simply keep track of values outside of your game's sta
```suggestion
DataStorage support is included in the library. You may save values on the archipelago server in order to share them across other player's sessions or to simply keep track of values outside of your game's state.
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +The DataStorage provides an interface based on keys and thier scope. by assinging a value to a key, that value is stored on the server, and by reading from a key a value is retrieved from the server.
```suggestion
The DataStorage provides an interface based on keys and their scope. By assigning a value to a key, that value is stored on the server and by reading from a key a value is retrieved from the server. 
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +The DataStorage also provides methods to retrieve the value of key asynchronously.
```suggestion
The DataStorage also provides methods to retrieve the value of a key asynchronously. 
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +If your intrested in keeping track of when a value of a certian key is changed you can use the `OnValueChanged` handler to register a callback for when the value gets updated.
```suggestion
If you're interested in keeping track of when a value of a certain key is changed you can use the `OnValueChanged` handler to register a callback for when the value gets updated.
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +* `+ Bitwise.LeftShift(x)`, binairy shift left to the left value by x
```suggestion
* `+ Bitwise.LeftShift(x)`, binary shift the value to the left by x
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +* `+ Bitwise.RightShift(x)`, binairy shift left to the right value by x
```suggestion
* `+ Bitwise.RightShift(x)`, binary shift the value to the right by x
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +mathematical operations, bitwise operations and callbacks can be chained, given the extended syntax with `()` around each operation
```suggestion
Mathematical operations, bitwise operations and callbacks can be chained, given the extended syntax with `()` around each operation.
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +examples:
```suggestion
Examples:
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +session.DataStorage[Scope.Global, "SetGlobal"] = 30; //Set `SetGlobal` to 30, in gloval scope shared amoung all players (the default scope is global)
```suggestion
session.DataStorage[Scope.Global, "SetGlobal"] = 30; //Set `SetGlobal` to 30, in global scope shared among all players (the default scope is global)
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +session.DataStorage["BitShiftLeft"] += Bitwise.LeftShift(1); //Divide current value of `BitShiftLeft` in half
```suggestion
session.DataStorage["BitShiftLeft"] += Bitwise.LeftShift(1); //Bitshift current value of  `BitShiftLeft` to left by 1
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +session.DataStorage["Xor"] += Bitwise.Xor(0xFF); //Moddify `Xor` using the Bitwise excluse or operation
```suggestion
session.DataStorage["Xor"] += Bitwise.Xor(0xFF); //Modify `Xor` using the Bitwise exclusive or operation
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +* `>>`, Override left with right value. if right value is lower
```suggestion
* `>>`, Override left with right value, if right value is lower
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +* `<<`, Override left with right value. if right value is bigger
```suggestion
* `<<`, Override left with right value, if right value is bigger
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +//Enerylink deplete pattern, Subtract 50, then set value to 0 if its lower than 0
```suggestion
//EnergyLink deplete pattern, subtract 50, then set value to 0 if its lower than 0
```

2022-03-14 22:36 UTC, Ijwu commented on README.md
> +//Handleing anonymous object, if the target type is not known you can use `To<JObject>()` and use its interface to access the members
```suggestion
//Handling anonymous object, if the target type is not known you can use `To<JObject>()` and use its interface to access the members
```

2022-03-15 21:27 UTC, Ijwu approved these changes
I am not willing to merge this in until 3.0 is merged in, but this is ready to go until then.

2022-03-16 00:49 UTC, JarnoWesthof commented
Not sure why you see a dependency with 3.0 but ok

2022-03-18 12:27 UTC, merged