More documentation
ArchipelagoMW/Archipelago.MultiClient.Net pull request #73
Opened 2022-11-02 23:36 UTC by toasterparty

Fixes #65

2022-11-03 00:02 UTC, alwaysintreble commented
~~now this just needs to teach me how to create my own in game console~~

2022-11-03 04:03 UTC, GGreenHeart commented
Spotted a few more typos! Haven't used github in a couple eons, so I'm just posting them here.

You have `Sout` instead of `Scout` in two places here: 
```
### Sout Location Checks
Souting means asking the server what is stored in a specific location *without* collecting it:
```

Misspelled `Location` as `Locaiton` here:
```
 ### Locaiton ID <--> Name
```

Mispelled `guaranteed` here:
```
Note: The list of received items will never shrink and the collection is garunteed to be in the order that the server sent the items. 
```

2022-11-05 17:01 UTC, Jarno458 requested changes

2022-11-05 17:01 UTC, Jarno458 commented on README.md
> +Note that `TryConnectAndLogin` issues an outgoing websocket connection attempt which can block the current thread for up to multiple seconds. If the client is implemented via code-injection (e.g. har
While this is not wrong, there are async methods available, they just require .net 4.0 or higher

`ConnectAsync()`
`LoginAsync(....)`

2022-11-06 11:19 UTC, Jarno458 approved these changes

2022-11-07 08:02 UTC, merged